---
- name: Installing Nginx.
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present
  notify: Restart Nginx

- name: Copying Nginx Configuration file.
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644

- name: Enable Configuration
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link
    mode: 0644
  changed_when: true
  notify: Restart Nginx

- name: Copying index.html file.
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{doc_root}}/index.html"
    mode: 0644